# Permanent link of posts
permalink: none

# Markdown rendering
markdown: redcarpet

# Syntax highlighting
highlighter: pygments

# Exclude non website files
exclude: ['.gitignore', 'Gemfile', 'README.md']

# The collections we are going to use for the documentation
collections:
  modules:
    output: true

# Defaults values
defaults:
  - scope:
      path: ""
      type: modules
    values:
      layout: module
